version: '3.8'
services:
  backend:
    build: ./backend/
    ports:
      - 5000:3000
    environment:
      - port=3000
      - URL_MONGOOSE=mongodb://mongo:27017
      - DBNAME=dbmovies
    depends_on:
      - mongo
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - vmongo:/data/db
volumes:
  vmongo:
