version: '3.8'
services:
  front:
    build: ./frontend/
    ports:
      - 3000:3000
    depends_on:
      - back
  back:
    build: ./backend/
    ports:
      - 5000:3000
    environment:
      - PORT=3000
      - URL_MONGOOSE=mongodb://mongo:27017
      - DBNAME=dbmovies
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - dbmovies:/data/db
volumes:
  dbmovies:
